dist: xenial
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"
  - "12"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - CXX="g++-4.8" CC="gcc-4.8"

after_script:
  - if [ "$TRAVIS_NODE_VERSION" = "12" ]; then npm run coveralls; fi

cache: npm
